name: build-kafka-images

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"

jobs:
  images-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set RELEASE_VERSION
        if: contains(github.ref, 'tags')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> ${GITHUB_ENV}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_NAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Set VERSIONS
        run: |
          if [ "${RELEASE_VERSION}" == "" ]; then
            echo "SCALA_VERSION=2.13" >> ${GITHUB_ENV}
            echo "KAFKA_VERSION=3.5.1" >> ${GITHUB_ENV}
            echo "RELEASE_VERSION=SNAPSHOT" >> ${GITHUB_ENV}
          else
            echo "SCALA_VERSION=$(echo ${RELEASE_VERSION} | cut -d '-' -f 1)" >> ${GITHUB_ENV}
            echo "KAFKA_VERSION=$(echo ${RELEASE_VERSION} | cut -d '-' -f 2)" >> ${GITHUB_ENV}
          fi
      - name: Docker build & push
        env:
          CI_REGISTRY: ghcr.io
          PROJECT_DIR: ${{ github.workspace }}
        run: |
          sudo apt update && sudo apt install curl
          chmod +x build-bin/image-build.sh
          build-bin/image-build.sh
