name: build-kafka-images

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"

jobs:
  images-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set RELEASE_VERSION
        if: contains(github.ref, 'tags')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> ${GITHUB_ENV}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_NAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Tools Installation
        run: |
          sudo apt update && sudo apt install curl
          curl -sL https://raw.githubusercontent.com/gissily/properties-tools/main/install.sh | sudo bash
      - name: Set VERSIONS
        run: |
          if [ "${RELEASE_VERSION}" == "" ]; then
            SCALA_VERSION=$(props value version.properties SCALA_VERSION)
            KAFKA_VERSION=$(props value version.properties KAFKA_VERSION)
            echo "SCALA_VERSION=${SCALA_VERSION}" >> ${GITHUB_ENV}
            echo "KAFKA_VERSION=${KAFKA_VERSION}" >> ${GITHUB_ENV}
            echo "RELEASE_VERSION=SNAPSHOT" >> ${GITHUB_ENV}
          else
            echo "SCALA_VERSION=$(echo ${RELEASE_VERSION} | cut -d '-' -f 1)" >> ${GITHUB_ENV}
            echo "KAFKA_VERSION=$(echo ${RELEASE_VERSION} | cut -d '-' -f 2)" >> ${GITHUB_ENV}
          fi
      - name: Docker build & push
        env:
          CI_REGISTRY: ghcr.io
          PROJECT_DIR: ${{ github.workspace }}
        run: |
          chmod +x .ci/image-build.sh
          .ci/image-build.sh
