name: build-kafka-images

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"

jobs:
  images-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set RELEASE_VERSION
        if: contains(github.ref, 'tags')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> ${GITHUB_ENV}
      - name: Set VERSIONS
        run: |
          if [ "${RELEASE_VERSION}" == "" ]; then
            echo "SCALA_VERSION=2.13" >> ${GITHUB_ENV}
            echo "KAFKA_VERSION=2.8.2" >> ${GITHUB_ENV}
            echo "RELEASE_VERSION=SNAPSHOT" >> ${GITHUB_ENV}
          else
            echo "SCALA_VERSION=$(echo ${RELEASE_VERSION} | cut -d '-' -f 1)" >> ${GITHUB_ENV}
            echo "KAFKA_VERSION=$(echo ${RELEASE_VERSION} | cut -d '-' -f 2)" >> ${GITHUB_ENV}
          fi
      - name: Docker build & push
        env:
          CI_DEPLOY_USER: ${{ secrets.CR_NAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CR_PAT }}
          CI_REGISTRY: ghcr.io
        run: |
          sudo apt update && sudo apt install curl
          echo ${CI_DEPLOY_PASSWORD} | docker login ${CI_REGISTRY} -u ${CI_DEPLOY_USER} --password-stdin
          chmod +x build-bin/image-build.sh
          build-bin/image-build.sh
